name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LOGIN: teste
      PASSWORD: teste
      DATABASE_URL: sqlite:///./test.db
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install --no-root --no-interaction

      - name: Rodar testes
        run: poetry run pytest
