name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LOGIN: teste
      PASSWORD: teste
      DATABASE_URL: sqlite:///./test.db

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install --no-root --no-interaction

      - name: Rodar testes
        run: poetry run pytest

      - name: Build do projeto
        run: poetry build
